steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
  
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: NONE
  
